// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzwhwUyXtnwpv6PovD0HrSTjfqRbEqTI',
    appId: '1:560412204249:web:e10b96b4ba8dfa638a72c8',
    messagingSenderId: '560412204249',
    projectId: 'hostelmanagement-76261',
    authDomain: 'hostelmanagement-76261.firebaseapp.com',
    storageBucket: 'hostelmanagement-76261.firebasestorage.app',
  );

  // ── Web (source: .env) ────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQeil2-v8fx1SIVG7EDuak4oCxJgUzQg',
    appId: '1:560412204249:android:2adb3f8e8df9abee8a72c8',
    messagingSenderId: '560412204249',
    projectId: 'hostelmanagement-76261',
    storageBucket: 'hostelmanagement-76261.firebasestorage.app',
  );

  // ── Android (source: google-services.json) ────────────────────────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAognr7GUXuVcgHH0h2bOWW7DrOsQbpGTo',
    appId: '1:560412204249:ios:9c0117116c0ae66a8a72c8',
    messagingSenderId: '560412204249',
    projectId: 'hostelmanagement-76261',
    storageBucket: 'hostelmanagement-76261.firebasestorage.app',
    iosBundleId: 'com.smarthostel.hostelManagement',
  );

  // ── iOS (source: .env — add GoogleService-Info.plist for exact iOS key) ───
}